name: Wafalyzer

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    container: crystallang/crystal
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: crystal spec
