name: Wafalyzer

on:
  push:
    branches:
      - dima/test-ci

jobs:
  build:
    runs-on: ubuntu-latest
    container: crystallang/crystal
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: crystal spec
